export enum SoknadsSti {
    OPPDATER_SAMTYKKE = "oppdaterSamtykker",
    HENT_SAMTYKKER = "hentSamtykker",
    ARBEID = "arbeid",
    BANKINFORMASJON = "personalia/kontonummer",
    BEGRUNNELSE = "begrunnelse",
    BOSITUASJON = "bosituasjon",
    UTDANNING = "utdanning",
    TELEFONNUMMER = "personalia/telefonnummer",
    BOSTOTTE = "inntekt/bostotte",
    BOSTOTTE_SAMTYKKE = "inntekt/bostotte/samtykke",
    STUDIELAN = "inntekt/studielan",
    UTBETALINGER = "inntekt/utbetalinger",
    VERDIER = "inntekt/verdier",
    FORMUE = "inntekt/formue",
    BOUTGIFTER = "utgifter/boutgifter",
    BARNEUTGIFTER = "utgifter/barneutgifter",
    ADRESSER = "personalia/adresser",
    NAV_ENHETER = "personalia/navEnheter",
    VALGT_NAV_ENHET = "personalia/navEnhet",
    SIVILSTATUS = "familie/sivilstatus",
    BASIS_PERSONALIA = "personalia/basisPersonalia",
    FORSORGERPLIKT = "familie/forsorgerplikt",
    INNTEKT_SYSTEMDATA = "inntekt/systemdata",
    SKATTBARINNTEKT = "inntekt/skattbarinntektogforskuddstrekk",
    SKATTBARINNTEKT_SAMTYKKE = "inntekt/skattbarinntektogforskuddstrekk/samtykke",
}
